# Generated by Django 5.1.3 on 2024-11-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='email', max_length=255)),
                ('password', models.CharField(db_column='pass', max_length=16)),
                ('username', models.CharField(db_column='username', max_length=255)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
