# Generated by Django 5.1.3 on 2024-12-26 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizhoot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('classroom', models.ForeignKey(db_column='classroom_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quizhoot.classroom')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message',
                'ordering': ['-timestamp'],
            },
        ),
    ]
