# Generated by Django 5.1.3 on 2024-11-26 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizhoot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_column='term', max_length=255)),
                ('definition', models.CharField(db_column='definition', max_length=255)),
                ('fav', models.BooleanField(db_column='fav_word', default=False)),
            ],
            options={
                'db_table': 'Flashcard',
            },
        ),
        migrations.CreateModel(
            name='Set_Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcard_id', models.ForeignKey(db_column='flashcard_id', on_delete=django.db.models.deletion.CASCADE, to='quizhoot.flashcard')),
                ('set_id', models.ForeignKey(db_column='set_id', on_delete=django.db.models.deletion.CASCADE, to='quizhoot.set')),
            ],
        ),
    ]
