# Generated by Django 5.1.3 on 2024-12-26 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizhoot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(db_column='message')),
                ('notification_type', models.CharField(choices=[('join_classroom', 'User joined classroom'), ('create_folder', 'Folder created'), ('add_set', 'Set added to folder'), ('custom', 'Custom notification')], db_column='notification_type', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('classroom', models.ForeignKey(blank=True, db_column='classroom_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='quizhoot.classroom')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
