# Generated by Django 5.1.3 on 2024-11-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizhoot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
