# Generated by Django 5.1.3 on 2024-11-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizhoot', '0002_flashcard_set_flashcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='fav',
        ),
        migrations.AddField(
            model_name='set_flashcard',
            name='fav',
            field=models.BooleanField(db_column='fav_word', default=False),
        ),
        migrations.AlterField(
            model_name='set',
            name='size',
            field=models.IntegerField(blank=True, db_column='size', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mindfulness',
            field=models.IntegerField(db_column='mindfulness', default=0, null=True),
        ),
    ]
