# Generated by Django 5.1.3 on 2024-12-23 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizhoot', '0002_quiz_alter_set_flashcard_user_id_quiz_user_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='corect_ans',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='incorrect_ans',
            new_name='incorrect_answer',
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(db_column='classroom_name', max_length=255)),
                ('creator_id', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='classroom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.BooleanField(db_column='user_role', default=False)),
                ('classroom_id', models.ForeignKey(db_column='classroom_id', on_delete=django.db.models.deletion.CASCADE, to='quizhoot.classroom')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
