# Generated by Django 5.1.3 on 2024-12-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizhoot', '0005_classroom_user_folders_classroom_user_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom_user',
            name='folders',
        ),
        migrations.RemoveField(
            model_name='classroom_user',
            name='sets',
        ),
        migrations.AddField(
            model_name='classroom',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='quizhoot.folder'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='quizhoot.set'),
        ),
    ]
