# Generated by Django 5.1.3 on 2024-11-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizhoot', '0006_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(db_column='set_name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('share', models.BooleanField(db_column='share', default=False)),
                ('tags', models.CharField(blank=True, db_column='tags', max_length=255, null=True)),
                ('language', models.CharField(blank=True, db_column='language', max_length=50, null=True)),
                ('rating', models.FloatField(blank=True, db_column='rating', null=True)),
                ('size', models.IntegerField(blank=True, db_column='size', null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='quizhoot.user')),
            ],
            options={
                'db_table': 'Set',
            },
        ),
    ]
